C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.1.3)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywraprow_prod (row_prodf2pywrap, i, j, ia, ja,
     & ra, w)
      external row_prod
      integer i
      integer j
      integer ia(*)
      integer ja(*)
      real*8 ra(*)
      real*8 w(*)
      real*8 row_prodf2pywrap
      real*8  row_prod
      row_prodf2pywrap = row_prod(i, j, ia, ja, ra, w)
      end


      subroutine f2pywrapdot (dotf2pywrap, x, y, mx, my, nx, ny, w
     &)
      external dot
      integer nx
      integer ny
      real*8 x(*)
      real*8 y(*)
      integer mx(*)
      integer my(*)
      real*8 w(*)
      real*8 dotf2pywrap
      real*8  dot
      dotf2pywrap = dot(x, y, mx, my, nx, ny, w)
      end


      subroutine f2pywrapdev2 (dev2f2pywrap, n, w, y, p, pmin)
      external dev2
      integer n
      real*8 pmin
      real*8 w(n)
      real*8 y(n)
      real*8 p(n)
      real*8 dev2f2pywrap
      real*8  dev2
      dev2f2pywrap = dev2(n, w, y, p, pmin)
      end


      subroutine f2pywrapazero (azerof2pywrap, n, y, g, q, jerr)
      external azero
      integer n
      integer jerr
      real*8 y(n)
      real*8 g(n)
      real*8 q(n)
      real*8 azerof2pywrap
      real*8  azero
      azerof2pywrap = azero(n, y, g, q, jerr)
      end


      subroutine f2pywrapelc (elcf2pywrap, parm, n, cl, a, m)
      external elc
      real*8 parm
      integer n
      real*8 cl(2)
      real*8 a(n)
      integer m(n)
      real*8 elcf2pywrap
      real*8  elc
      elcf2pywrap = elc(parm, n, cl, a, m)
      end


      subroutine f2pywrapnintot (nintotf2pywrap, ni, nx, nc, a, m,
     & nin, is)
      external nintot
      integer ni
      integer nx
      integer nc
      integer nin
      real*8 a(nx,nc)
      integer m(nx)
      integer is(ni)
      integer nintotf2pywrap
      integer  nintot
      nintotf2pywrap = nintot(ni, nx, nc, a, m, nin, is)
      end


      subroutine f2pywraprisk (riskf2pywrap, no, ni, nk, d, dk, f,
     & e, kp, jp, u)
      external risk
      integer no
      integer ni
      integer nk
      real*8 d(no)
      real*8 dk(nk)
      real*8 f(no)
      real*8 e(no)
      integer kp(nk)
      integer jp(no)
      real*8 u(nk)
      real*8 riskf2pywrap
      real*8  risk
      riskf2pywrap = risk(no, ni, nk, d, dk, f, e, kp, jp, u)
      end


      subroutine f2pywrapnonzero (nonzerof2pywrap, n, v)
      external nonzero
      integer n
      real*8 v(n)
      integer nonzerof2pywrap
      integer  nonzero
      nonzerof2pywrap = nonzero(n, v)
      end


      subroutine f2pywrapbnorm (bnormf2pywrap, b0, al1p, al2p, g, 
     &usq, jerr)
      external bnorm
      real*8 b0
      real*8 al1p
      real*8 al2p
      real*8 g
      real*8 usq
      integer jerr
      real*8 bnormf2pywrap
      real*8  bnorm
      bnormf2pywrap = bnorm(b0, al1p, al2p, g, usq, jerr)
      end

