language: python
dist: xenial

os:
  - linux

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libopenblas-dev
      - libopenblas-base

env:
  global:
    - CIBW_SKIP="*-win32 *-manylinux_i686 cp27-*"
    - TWINE_USERNAME=__token__

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell

install:
  - python3 -m pip install twine cibuildwheel==1.1.0

script:
  - python3 -m cibuildwheel --output-dir wheelhouse
  # needed to run setup.py sdist
  - python3 -m pip install numpy
  - python3 setup.py sdist --formats=gztar

notifications:
    email: false

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python3 -m twine upload wheelhouse/*.whl dist/*.tar.gz; fi
