#!/usr/bin/env python

from __future__ import print_function, division

import sys
import os

import numpy as np

from harmonization.config import read_config, write_config, get_filenames
from harmonization.dictionary import get_global_D


def main():

    if len(sys.argv) == 1:
        usage = 'Usage : everything is set in config.yaml, that is the only input.'
        print(usage)
        sys.exit(1)

    config = sys.argv[1]

    if len(sys.argv) == 3:
        path = sys.argv[2]
        if config == 'write':
            write_config(path)
            print('Default config written at {}'.format(os.path.abspath(path)))
            sys.exit(1)
        else:
            error = 'You need to pass the keyword [write] as an argument followed by a filename to write the default config, but you passed {}'.format(sys.argv[1:])
            raise ValueError(error)

    kwargs = read_config(config)

    # we need to do a few special things for some args
    path = kwargs.pop('path')
    use_glob = kwargs.pop('glob')
    outfilename = kwargs.pop('outfilename')

    datasets = get_filenames(path, use_glob)

    D = get_global_D(datasets, outfilename, **kwargs)
    np.save(outfilename, D)


if __name__ == "__main__":
    main()
