#!/usr/bin/env python

from __future__ import print_function, division

import sys

from harmonization.config import read_config, get_filenames
from harmonization.dictionary import harmonize_my_data


def main():

    if len(sys.argv) == 1:
        usage = 'Usage : everything is set in config.yaml, that is the only input.'
        print(usage)
        sys.exit(1)

    config = sys.argv[1]
    kwargs = read_config(config)

    path = kwargs.pop('path')
    use_glob = kwargs.pop('glob')
    kwargs.pop('positivity_D')
    kwargs['positivity'] = kwargs.pop('positivity_recon')

    datasets = get_filenames(path, use_glob, kwargs)

    # Actually harmonize each dataset by itself
    for dataset in datasets:
        harmonize_my_data(dataset, kwargs)


if __name__ == "__main__":
    main()
