name: Build and upload to PyPI

on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]
        pyver: ['cp310', 'cp311', 'cp312', 'cp313', 'cp314', 'cp315']
        toolchain:
            - {compiler: gcc, version: 13}

    steps:
      - uses: actions/checkout@v7

      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Mac os deployment target
        if: runner.os == 'macOS'
        run: echo "MACOSX_DEPLOYMENT_TARGET=15.0" >> "$GITHUB_ENV"

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "${{matrix.pyver}}-*"

      - uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Test against oldest supported numpy version
        if: ${{ matrix.pyver == 'cp311' }}
        shell: bash
        run: |
            python -m pip install ./wheelhouse/*${{matrix.pyver}}*.whl
            python -m pip install numpy==2.0 scipy==1.8 pytest
            pytest --pyargs harmonization

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-harmonization_${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        name: Install Python
        with:
          python-version: '3.13'

      - name: Build sdist
        run: |
          python -m pip install build pdoc
          python -m build --sdist

      - name: Make doc
        run: pdoc harmonization/ -o docs/

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy_doc:
    needs: build_sdist
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  publish_artifacts:
    name: publish to pypi and github release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    # upload to PyPI on every tag starting with 'v'
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    steps:
      - name: Download builds
        uses: actions/download-artifact@v7
        with:
          path: dist/
          pattern: cibw-*
          merge-multiple: true

      # See also https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      - name: upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: publish to github release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
